# Generated by Django 2.2.5 on 2020-12-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201207_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_confirmed',
            new_name='email_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='eamil_secret',
            field=models.CharField(blank=True, default='', max_length=34),
        ),
    ]
