# Generated by Django 2.2.5 on 2020-12-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201207_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='eamil_secret',
            new_name='email_secret',
        ),
    ]
