# Generated by Django 2.2.5 on 2020-10-09 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201009_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='langeuage',
            new_name='language',
        ),
    ]
