# Generated by Django 2.2.5 on 2020-10-12 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20201012_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='hosue_rule',
            new_name='house_rules',
        ),
    ]
