# Generated by Django 2.2.5 on 2020-12-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20201014_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='guests',
            field=models.IntegerField(help_text='how many people will be staying?'),
        ),
    ]
