# Generated by Django 2.2.5 on 2020-12-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20201013_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confrimed'), ('canceled', 'Canceled')], default='pending', max_length=12),
        ),
    ]
